import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { defineCommand } from 'citty';

export type AuditPresetName = 'shadcn' | 'prettyfly';

const PRESET_NAMES: readonly AuditPresetName[] = ['shadcn', 'prettyfly'];

const TEMPLATES: Record<AuditPresetName, string> = {
  shadcn: `import { shadcnDefaults } from '@atelier-oss/audit';
import type { AuditConfig } from '@atelier-oss/audit';

/**
 * Atelier audit configuration — generated by \`atelier audit init --preset shadcn\`.
 *
 * Edit any field below to override the shadcn-style defaults. Pass this object
 * to \`audit({ root, ...config })\` or run \`atelier audit\` with this file present.
 */
const config: Omit<AuditConfig, 'root'> = {
  ...shadcnDefaults(),
  // componentDir: 'app/components',  // override if your shadcn dir is non-standard
  // contrastSamples: [...],          // pass actual surface colors for accurate contrast
};

export default config;
`,
  prettyfly: `import { prettyflyDefaults } from '@atelier-oss/audit';
import type { AuditConfig } from '@atelier-oss/audit';

/**
 * Atelier audit configuration — generated by \`atelier audit init --preset prettyfly\`.
 *
 * Reproduces the prettyfly-os Mission Control home dashboard defaults from
 * \`benchmarks/audit_home_dashboard.py\`. Use this preset only if your project
 * has the same layout (components/home/command-center/CommandSphere.tsx, etc.).
 */
const config: Omit<AuditConfig, 'root'> = {
  ...prettyflyDefaults(),
};

export default config;
`,
};

export interface RunAuditInitOptions {
  cwd: string;
  preset?: AuditPresetName;
  force?: boolean;
}

export interface RunAuditInitResult {
  written: string;
  alreadyExisted: boolean;
}

export function runAuditInit(options: RunAuditInitOptions): RunAuditInitResult {
  const preset = options.preset ?? 'shadcn';
  if (!PRESET_NAMES.includes(preset)) {
    throw new Error(
      `unknown preset: ${preset}. Valid presets: ${PRESET_NAMES.join(', ')}.`,
    );
  }

  const target = join(options.cwd, 'atelier.audit.config.ts');
  const existed = existsSync(target);
  if (existed && !options.force) {
    return { written: target, alreadyExisted: true };
  }

  writeFileSync(target, TEMPLATES[preset], 'utf-8');
  return { written: target, alreadyExisted: false };
}

export const auditInitCommand = defineCommand({
  meta: {
    name: 'init',
    description: 'Scaffold atelier.audit.config.ts in the current directory.',
  },
  args: {
    preset: {
      type: 'string',
      description: `Preset to scaffold: ${PRESET_NAMES.join(' | ')}. Default: shadcn.`,
      default: 'shadcn',
    },
    force: {
      type: 'boolean',
      description: 'Overwrite an existing atelier.audit.config.ts.',
      default: false,
    },
  },
  run({ args }) {
    const preset = args.preset as AuditPresetName;
    if (!PRESET_NAMES.includes(preset)) {
      console.error(
        `unknown preset: ${preset}. Valid presets: ${PRESET_NAMES.join(', ')}.`,
      );
      process.exit(2);
    }
    try {
      const result = runAuditInit({ cwd: process.cwd(), preset, force: args.force });
      if (result.alreadyExisted) {
        console.error(
          `atelier.audit.config.ts already exists at ${result.written}. Pass --force to overwrite.`,
        );
        process.exit(1);
      }
      console.log(`wrote ${result.written}`);
    } catch (err) {
      console.error(err instanceof Error ? err.message : String(err));
      process.exit(2);
    }
  },
});
